//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Upchurch.Ingress.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Upchurch.Ingress.Tests.JsonResource", typeof(JsonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;&quot;result&quot;&quot;:&quot;&quot;1450066218367&quot;&quot;,&quot;&quot;gameBasket&quot;&quot;:{&quot;&quot;gameEntities&quot;&quot;:[],&quot;&quot;inventory&quot;&quot;:[[&quot;&quot;519073bec8744d1b9dc4a9c0a4d8125d.5&quot;&quot;,1446513224694,{&quot;&quot;displayName&quot;&quot;:{&quot;&quot;displayName&quot;&quot;:&quot;&quot;Power Cube&quot;&quot;,&quot;&quot;displayDescription&quot;&quot;:&quot;&quot;Store of XM which can be used to recharge Scanner.&quot;&quot;},&quot;&quot;resourceWithLevels&quot;&quot;:{&quot;&quot;resourceType&quot;&quot;:&quot;&quot;POWER_CUBE&quot;&quot;,&quot;&quot;level&quot;&quot;:8},&quot;&quot;accessLevel&quot;&quot;:{&quot;&quot;requiredLevel&quot;&quot;:8,&quot;&quot;failure&quot;&quot;:{&quot;&quot;isAllowed&quot;&quot;:false,&quot;&quot;requiredLevel&quot;&quot;:8}},&quot;&quot;powerCube&quot;&quot;:{&quot;&quot;energy&quot;&quot;:8000},&quot;&quot;inInventory&quot;&quot;:{&quot;&quot;playerId&quot;&quot;:&quot;&quot;0d380215dc7f4296bfdf132a [rest of string wa....
        /// </summary>
        internal static string InventoryJson {
            get {
                return ResourceManager.GetString("InventoryJson", resourceCulture);
            }
        }
    }
}
